version: '3.9'
services:
  redis:
    image: redis:latest
    container_name: redis_service
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 3
      timeout: 5s
      start_period: 5s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    ports:
      - "8081:8081"
    environment:
      REDIS_HOST: redis
    depends_on:
      redis:
        condition: service_healthy
